### ISSUE TITLE
The Twilight Forest - Deforestation Edition crash issue

### ISSUE THREAD

**Issue by touhouzun** [CaliforniaDemise/twilightforest#1]
Forge version: 1.12.2-forge1.12.2-14.23.5.2860
Twilight Forest version: twilightforest-1.12.2-3.11.1-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
https://gist.github.com/touhouzun/c08047791b50855fa753bbd563bb555e
Steps to reproduce:
1. throw twilightforest-1.12.2-3.11.1-universal into mod filter
2. launch with BakaXL_Public_Ver_3.5.1.0
What I expected to happen:
launch without issues
What happened instead:
crash without any other mods

**Comment by CaliforniaDemise** [comment]
Does this bug occur in normal twilight forest?

**Comment by touhouzun** [comment]
> Does this bug occur in normal twilight forest?

Well, no.
You can always believe in TeamTwilightForest's heritage.
...except for the doors-_-|| 

I'll try again tomorrow.

**Comment by CaliforniaDemise** [comment]
No need. I found what the issue is. I posted the wrong jar.
