### ISSUE TITLE
[Feature Request] `Sorting Tree` integration

### ISSUE THREAD

**Issue by Krutoy242** [CaliforniaDemise/twilightforest#3]
Most of Twilight Forest unique mechanic are awesome, but lack of integrations, what makes TF one of the most underrated mods in big modpacks like E2E.
Adding more connections would help to give second life to such old mod.

**Sorting Tree** should be able to sort any common inventories, not only vanilla chests. If this is impossible, at least list of valid containers should be provided, like Rustic's Cabinets or Actually Addition's "Small" Storage Crates.

![image](https://github.com/user-attachments/assets/52c1cc4d-eab3-4ae0-978c-19ffdc862161)

Please answer if you would be willing to add this feature.

[Original post.](https://github.com/Invadermonky/MagicultureIntegrations/issues/5)

**Comment by CaliforniaDemise** [comment]
Yes, adding integrations for stuffs like trees and magnets are planned.

**Comment by CaliforniaDemise** [comment]
[Tthis commit](https://github.com/CaliforniaDemise/twilightforest/commit/b871b955b4bf6a14f856f70e508712ffa18943a9) makes sorting tree work for all storage tile entities.
I will add an API for unconventional tile entities and maybe also make it work with entities too.

**Comment by Krutoy242** [comment]
So, I only should wait for next CF release?

**Comment by CaliforniaDemise** [comment]
yeah, it might take a while though because I'm busy with other mods.

**Comment by Krutoy242** [comment]
How I can install mod version with this feature implemented?

**Comment by Krutoy242** [comment]
I see that new implementation is lack of features. Its not moving items between chests anymore!
Why so? now it only combine items in a single inventory, which is kinda useless.

**Comment by CaliforniaDemise** [comment]
Please create new issue report when new issues occur. I don't follow closed ones.
