### ISSUE TITLE
Crash with Twilight Tweaks

### ISSUE THREAD

**Issue by beltxd** [CaliforniaDemise/twilightforest#4]
https://mclo.gs/GUxaieb

Reproduced with latest versions of Twilight forest Deforestation + Twilight tweaks.

**Comment by beltxd** [comment]
Additionally, could a configurable damage option be added for the Hydra as well, for its projectiles and base damage

**Comment by CaliforniaDemise** [comment]
I will add whole Twilight Tweaks to this fork. You will need to change some stuff though. I will make a migration guide too.

**Comment by CaliforniaDemise** [comment]
You can look [here](https://github.com/CaliforniaDemise/twilightforest/tree/1.12.x/script_examples) for crafttweaker support, I'll add groovyscript support later.
