### ISSUE TITLE
Continuous crashs in Knight Phantom structure (Goblin Knight Stronghold)

### ISSUE THREAD

**Issue by JoeKerr34** [CaliforniaDemise/twilightforest#5]
Be sure to use latest Forge version and Twilight Forest version.
Post crash report (or if there isn't log) to places such as [mclo.gs](https://mclo.gs) or [gist](https://gist.github.com/).

Steps to reproduce:
1. I beat the Naga, Lich, Minoshroom, Yeti, Hydra, then tried to beat the Knight Phantoms
2. Didn't crash until layer 3 or 4.
3. Continuous crashing
4. Downloaded with Curseforge and didn't download the original Twilight Forest mod (idk if relevant but just want to mention)

What I expected to happen:
Not crash/load the wraith

What happened instead:
The game crashed whilst rendering entity in world
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.RenderLivingBase.field_77045_g from class twilightforest.client.renderer.entity.RenderTFWraith$LayerWraith
Error Code: -1

**Comment by CaliforniaDemise** [comment]
Already fixed.
